import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { describe, test } from 'node:test';

import { convertDdl, convertSchema, convertStatement, mapType, parseColumnDef } from '../src/schema.js';
import { splitStatements } from '../src/sqlparse.js';

const fixture = (name) => readFile(new URL(`./fixtures/${name}`, import.meta.url), 'utf8');
const one = (sql, opts) => convertStatement(sql, { tables: new Map(), usesPgcrypto: false, notes: [] }, opts);
const strip = (s) => s.replace(/^--.*\n/gm, '').replace(/\s+/g, ' ').trim();

describe('type mapping', () => {
  test('the affinity-style rules', () => {
    assert.equal(mapType('INTEGER'), 'bigint');
    assert.equal(mapType('int'), 'bigint');
    assert.equal(mapType('UNSIGNED BIG INT'), 'bigint');
    assert.equal(mapType('REAL'), 'double precision');
    assert.equal(mapType('FLOAT'), 'double precision');
    assert.equal(mapType('BLOB'), 'bytea');
    assert.equal(mapType('BOOLEAN'), 'boolean');
    assert.equal(mapType('DATETIME'), 'timestamptz');
    assert.equal(mapType('TIMESTAMP'), 'timestamptz');
    assert.equal(mapType('DATE'), 'date');
    assert.equal(mapType('TEXT'), 'text');
    assert.equal(mapType('VARCHAR(255)'), 'text');
    assert.equal(mapType('NVARCHAR(10)'), 'text');
    assert.equal(mapType('CLOB'), 'text');
    assert.equal(mapType(''), 'text');
    assert.equal(mapType('NUMERIC(10,2)'), 'numeric(10,2)');
    assert.equal(mapType('DECIMAL'), 'numeric');
    assert.equal(mapType('JSON'), 'text');
    assert.equal(mapType('JSON', { json: 'jsonb' }), 'jsonb');
    assert.equal(mapType('UUID'), 'uuid');
  });
  test('parseColumnDef splits name, type and constraints', () => {
    assert.deepEqual(parseColumnDef('"order" INTEGER NOT NULL DEFAULT 0'), { name: 'order', declared: 'INTEGER', constraints: 'NOT NULL DEFAULT 0' });
    assert.deepEqual(parseColumnDef('name'), { name: 'name', declared: '', constraints: '' });
    assert.deepEqual(parseColumnDef('price NUMERIC(10, 2) CHECK (price > 0)'), { name: 'price', declared: 'NUMERIC(10, 2)', constraints: 'CHECK (price > 0)' });
  });
});

describe('CREATE TABLE', () => {
  test('INTEGER PRIMARY KEY AUTOINCREMENT and INTEGER PRIMARY KEY become identity columns', () => {
    assert.equal(strip(one('CREATE TABLE a (id INTEGER PRIMARY KEY AUTOINCREMENT, x TEXT)')), 'create table a ( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, x text );');
    assert.equal(strip(one('create table b (id integer primary key, x text)')), 'create table b ( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, x text );');
    assert.equal(strip(one('create table c (id integer not null primary key desc)')), 'create table c ( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null );');
  });
  test('a table-level single-column integer PRIMARY KEY is an identity column too', () => {
    assert.equal(strip(one('create table s (id integer not null, l text, primary key (id autoincrement))')), 'create table s ( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null, l text );');
  });
  test('a text primary key stays a plain primary key; composite keys are kept', () => {
    assert.equal(strip(one('create table u (id text primary key, n text)')), 'create table u ( id text PRIMARY KEY, n text );');
    assert.equal(strip(one('create table t (a integer, b text, primary key (a, b))')), 'create table t ( a bigint, b text, primary key (a, b) );');
  });
  test('AUTOINCREMENT is removed anywhere', () => {
    assert.doesNotMatch(one('create table a (id integer primary key autoincrement, n integer autoincrement)'), /autoincrement/i);
  });
  test('DEFAULT expressions', () => {
    const out = strip(
      one(
        "create table d (a text default (datetime('now')), b datetime default current_timestamp, c integer default (strftime('%s','now')), e text default (lower(hex(randomblob(16)))), f boolean default 1, g boolean default 0, h text default 'x', i real default 0.5, j integer default (unixepoch()))",
      ),
    );
    assert.match(out, /a timestamptz default now\(\)/i);
    assert.match(out, /b timestamptz default now\(\)/i);
    assert.match(out, /c bigint default \(extract\(epoch from now\(\)\)::bigint\)/i);
    assert.match(out, /e text default \(encode\(gen_random_bytes\(16\), 'hex'\)\)/i);
    assert.match(out, /f boolean default true/i);
    assert.match(out, /g boolean default false/i);
    assert.match(out, /h text default 'x'/i);
    assert.match(out, /i double precision default 0\.5/i);
    assert.match(out, /j bigint default \(extract\(epoch from now\(\)\)::bigint\)/i);
  });
  test('a TEXT column with a current-time default is promoted to timestamptz unless told not to', () => {
    assert.match(strip(one("create table p (t text default (datetime('now')))")), /t timestamptz/);
    assert.match(strip(one("create table p (t text default (datetime('now')))", { promoteTextTimestamps: false })), /t text default now\(\)/i);
  });
  test('WITHOUT ROWID and STRICT are dropped; COLLATE NOCASE is dropped with a note; column ON CONFLICT is dropped', () => {
    const out = one('create table w (k text primary key collate nocase, v integer default 0 on conflict replace) without rowid');
    const code = strip(out);
    assert.doesNotMatch(code, /without rowid/i);
    assert.doesNotMatch(code, /nocase/i);
    assert.doesNotMatch(code, /on conflict/i);
    assert.match(out, /-- k: dropped COLLATE NOCASE/);
    assert.match(out, /-- dropped WITHOUT ROWID/);
  });
  test('a boolean check (x in (0,1)) is dropped, an integer one kept', () => {
    assert.doesNotMatch(one('create table b (f boolean not null default 0 check (f in (0, 1)))'), /check/i);
    assert.match(one('create table b (f integer not null default 0 check (f in (0, 1)))'), /check \(f in \(0, 1\)\)/i);
  });
  test('references, foreign keys, unique and check constraints pass through', () => {
    const out = strip(one('create table c (id integer primary key, u integer references users(id) on delete cascade, s text, unique (u, s), check (length(s) > 0), foreign key (u) references users (id))'));
    assert.match(out, /u bigint REFERENCES users\(id\) ON DELETE CASCADE/i);
    assert.match(out, /UNIQUE \(u, s\)/i);
    assert.match(out, /CHECK \(length\(s\) > 0\)/i);
    assert.match(out, /FOREIGN KEY \(u\) REFERENCES users \(id\)/i);
  });
  test('reserved column names and quoted names are quoted', () => {
    const out = strip(one('create table r ("order" integer, user text, `Mixed` text, [bracket] text)'));
    assert.match(out, /"order" bigint/);
    assert.match(out, /"user" text/);
    assert.match(out, /"Mixed" text/);
    assert.match(out, /\bbracket text/);
  });
  test('a generated column becomes STORED', () => {
    assert.match(strip(one('create table g (a integer, b integer generated always as (a * 2) virtual, c integer as (a + 1))')), /b bigint GENERATED ALWAYS AS \(a \* 2\) STORED, c bigint GENERATED ALWAYS AS \(a \+ 1\) STORED/);
  });
  test('an unknown declared type maps to text with a note', () => {
    const out = one('create table u (x MYSTERY)');
    assert.match(out, /x text/);
    assert.match(out, /unknown type "MYSTERY"/);
  });
  test('IF NOT EXISTS and TEMP are kept', () => {
    assert.match(strip(one('create temp table if not exists t (a text)')), /^create temporary table if not exists t/);
  });
});

describe('indexes, views, alter, virtual tables, triggers', () => {
  test('CREATE INDEX IF NOT EXISTS is kept; COLLATE NOCASE becomes lower()', () => {
    assert.equal(one('CREATE INDEX IF NOT EXISTS i ON t (a, b DESC)'), 'CREATE INDEX IF NOT EXISTS i ON t (a, b DESC);');
    assert.equal(one('create unique index u on t (name collate nocase)'), 'create unique index u on t (lower(name));');
  });
  test('ALTER TABLE ADD COLUMN maps the type and default', () => {
    assert.equal(strip(one("alter table t add column c text default (datetime('now'))")), 'alter table t add column if not exists c timestamptz default now();');
    assert.equal(strip(one('alter table t add flag boolean not null default 0')), 'alter table t add column if not exists flag boolean not null default false;');
  });
  test('a view body gets the function rewrites', () => {
    assert.equal(one("create view v as select id from t where c > datetime('now', '-1 day')"), "create view v as select id from t where c > (now() - interval '1 day');");
  });
  test('FTS5 with content= becomes a tsvector column and GIN index on that table', () => {
    const ctx = { tables: new Map([['posts', { name: 'posts', columns: new Map([['title', 'text'], ['body', 'text'], ['n', 'bigint']]) }]]), usesPgcrypto: false, notes: [] };
    const out = convertStatement("create virtual table posts_fts using fts5(title, body, n, slug unindexed, content='posts', content_rowid='id')", ctx);
    assert.match(out, /alter table posts add column if not exists search tsvector/);
    assert.match(out, /coalesce\(title, ''\) \|\| ' ' \|\| coalesce\(body, ''\) \|\| ' ' \|\| coalesce\(n::text, ''\)/);
    assert.match(out, /create index if not exists posts_search_idx on posts using gin \(search\)/);
    assert.match(out, /-- create virtual table/i);
    assert.doesNotMatch(strip(out), /slug/i);
  });
  test('FTS5 without content= finds the table by stripping _fts', () => {
    const ctx = { tables: new Map([['docs', { name: 'docs', columns: new Map([['body', 'text']]) }]]), usesPgcrypto: false, notes: [] };
    assert.match(convertStatement('create virtual table docs_fts using fts5(body)', ctx), /alter table docs add column/);
  });
  test('FTS5 with no findable table is a TODO', () => {
    const out = one('create virtual table things_fts using fts5(a, b)');
    assert.match(out, /TODO: could not find the content table/);
    assert.match(out, /to_tsvector/);
  });
  test('another virtual module is a TODO', () => {
    assert.match(one('create virtual table geo using rtree(id, minx, maxx)'), /TODO: virtual table "geo" uses rtree/);
  });
  test('triggers are commented with a TODO, and an FTS-maintaining one says so', () => {
    const fts = one('CREATE TRIGGER t_ai AFTER INSERT ON t BEGIN INSERT INTO t_fts(rowid, a) VALUES (new.id, new.a); END');
    assert.match(fts, /^-- TODO: trigger "t_ai": it maintained an FTS5 table/);
    assert.ok(fts.split('\n').every((l) => l.startsWith('--')));
    const other = one("CREATE TRIGGER t_au AFTER UPDATE ON t BEGIN UPDATE t SET u = datetime('now') WHERE id = new.id; END");
    assert.match(other, /rewrite as a Postgres trigger function/);
  });
  test('PRAGMA, BEGIN, COMMIT and sqlite_sequence are dropped', () => {
    assert.equal(one('PRAGMA foreign_keys = ON'), null);
    assert.equal(one('BEGIN TRANSACTION'), null);
    assert.equal(one('COMMIT'), null);
    assert.equal(one("DELETE FROM sqlite_sequence WHERE name = 'x'"), null);
  });
  test('seed rows go through the DML rewriter', () => {
    assert.equal(one("insert or ignore into c (k, v) values ('a', 1)"), "INSERT INTO c (k, v) values ('a', 1) ON CONFLICT DO NOTHING;");
  });
});

describe('the whole fixture', () => {
  test('splitStatements keeps trigger bodies whole', () => {
    const stmts = splitStatements('create table a (x); create trigger t after insert on a begin update a set x = 1; delete from a where x = 2; end; select 1;');
    assert.equal(stmts.length, 3);
    assert.match(stmts[1], /^create trigger[\s\S]*end$/i);
  });
  test('converts blog.sqlite.sql into the expected Postgres file', async () => {
    const out = convertSchema(await fixture('blog.sqlite.sql'));
    const expected = await fixture('blog.postgres.sql');
    assert.equal(out, expected);
  });
  test('converting the converted file again changes nothing (the client runs run-time DDL through it)', async () => {
    const once = convertSchema(await fixture('blog.sqlite.sql'));
    const twice = convertSchema(once);
    const code = (s) => s.split('\n').filter((l) => !l.trim().startsWith('--')).join('\n').replace(/\s+/g, ' ').trim().toLowerCase();
    assert.equal(code(twice), code(once));
  });
  test('pgcrypto is only requested when gen_random_bytes is used', () => {
    assert.doesNotMatch(convertSchema('create table t (a text)'), /pgcrypto/);
    assert.match(convertSchema('create table t (a text default (lower(hex(randomblob(8)))))'), /create extension if not exists pgcrypto/);
  });
  test('convertDdl handles a single statement issued at run time', () => {
    assert.match(convertDdl("CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY, v TEXT, at TEXT DEFAULT (datetime('now')))"), /at timestamptz DEFAULT now\(\)/);
    assert.equal(convertDdl('PRAGMA x'), '');
  });
});
