-- Converted from SQLite by @profullstack/libsql-pg. Review every TODO before applying.
-- Types: INTEGER -> bigint, REAL -> double precision, BLOB -> bytea, BOOLEAN -> boolean,
-- DATETIME/TIMESTAMP -> timestamptz, TEXT -> text; INTEGER PRIMARY KEY -> identity.

create extension if not exists pgcrypto;

-- created_at: text column with a current-time default became timestamptz
-- email: dropped COLLATE NOCASE
-- is_admin: default 0 -> false
-- created_at: default (datetime('now')) -> now()
-- updated_at: default CURRENT_TIMESTAMP -> now()
-- last_seen: default (strftime('%s','now')) -> (extract(epoch from now())::bigint)
-- api_key: default (lower(hex(randomblob(16)))) -> (encode(gen_random_bytes(16), 'hex'))
create table if not exists users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  name text,
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  last_seen bigint DEFAULT (extract(epoch from now())::bigint),
  api_key text DEFAULT (encode(gen_random_bytes(16), 'hex')),
  settings text
);

-- dropped WITHOUT ROWID
create table posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slug text NOT NULL,
  title text NOT NULL,
  body text,
  score double precision DEFAULT 0.0,
  cover bytea,
  published bigint NOT NULL DEFAULT 0 CHECK (published IN (0, 1)),
  published_at timestamptz,
  "order" bigint,
  UNIQUE (user_id, slug)
);

create table tags (
  post_id bigint NOT NULL,
  tag text NOT NULL,
  PRIMARY KEY (post_id, tag),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- value: dropped column conflict clause "ON CONFLICT REPLACE"
-- dropped STRICT
create table counters (
  "key" text PRIMARY KEY,
  value bigint NOT NULL DEFAULT 0
);

create table seq_style (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  label text
);

CREATE INDEX IF NOT EXISTS posts_user_idx ON posts (user_id, published_at DESC);

CREATE UNIQUE INDEX users_name_idx ON users (lower(name));

-- FTS5 table "posts_fts" (title, body) has no Postgres counterpart; it is replaced below.
-- CREATE VIRTUAL TABLE posts_fts USING fts5(title, body, slug UNINDEXED, content='posts', content_rowid='id')
alter table posts add column if not exists search tsvector
  generated always as (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))) stored;
create index if not exists posts_search_idx on posts using gin (search);
-- query: where search @@ websearch_to_tsquery('english', ?) order by ts_rank_cd(search, websearch_to_tsquery('english', ?)) desc

-- TODO: trigger "posts_ai": it maintained an FTS5 table, which the generated tsvector column replaces; probably drop it
-- CREATE TRIGGER posts_ai AFTER INSERT ON posts BEGIN
--   INSERT INTO posts_fts(rowid, title, body) VALUES (new.id, new.title, new.body);
-- END

-- TODO: trigger "posts_touch": rewrite as a Postgres trigger function (create function ... returns trigger, then create trigger ... execute function)
-- CREATE TRIGGER posts_touch AFTER UPDATE ON posts BEGIN
--   UPDATE posts SET published_at = CASE WHEN new.published = 1 THEN datetime('now') ELSE NULL END WHERE id = new.id;
-- END

CREATE VIEW recent_posts AS SELECT id, title FROM posts WHERE created_at > (now() - interval '7 days');

alter table users add column if not exists bio text DEFAULT '';

INSERT INTO counters (key, value) VALUES ('visits', 0) ON CONFLICT DO NOTHING;
